Add fractional ephemeris rate observation request language to NEOExchange
LCOGT/neoexchange pull request #598
Opened 2022-01-25 22:20 UTC by jchate6

- Sets half rate to default
- adds rate selection to submission page (Additional options)
- splits configurations to ensure the target never leaves the FOV
- Split Instrument configurations so they progress in the expected way 

[NOTE: this currently does not split up instrument configurations with multiple exposures. For example, a 10 exposure block, split into 2 [5,5] exposure configurations, with the expected filter pattern of [V,R] will be unchanged (V,R,V,R,V,)(R,V,R,V,R), but filter pattern of [VV,RR] will not finish a partially completed pattern and result in (V,V,R,R,V)(R,R,V,V,R)]

Still TODO:
- [ ] Add "rate" model field to `Block`
- [ ] More Tests (MuSCAT, edge cases, spectroscopy)
- [ ] deploy to Dev

2022-02-02 23:05 UTC, talister requested changes
Requested changes as discussed in the Zoom call of 2/2/2022. Need for more comprehensive functional tests around the "schedule form->schedule submit->block recording" sections noted but not to be implemented on this branch...

2022-02-02 23:05 UTC, talister commented on neoexchange/core/migrations/0064_auto_20220128_2217.py
> +class Migration(migrations.Migration):
Think it's worth putting a comment in this class to say that this is a Data Migration and include a link to the docs (https://docs.djangoproject.com/en/3.1/topics/migrations/#data-migrations)

2022-02-04 22:49 UTC, jchate6 commented on neoexchange/core/templates/core/schedule_confirm.html
>                                  <table align="right"  style="margin: 0px"><tr><td></td><td class="kv-value"><div class="tooltip">
Done

2022-02-05 00:59 UTC, jchate6 commented
Aside from failing docker containers, I think this looks pretty good, if you want to give another look next week.

2022-03-11 00:29 UTC, merged